### ISSUE TITLE
Interesting work!

### ISSUE THREAD

**Issue by vaseline555** [BorgwardtLab/JointMDS#2]
Dear authors,
I've really enjoyed reading your work.

Out of my curiosity, I wonder whether this work can be extended to align multiple datasets with no given correspondence.
To be more specific, is this scenario viable by only replacing Wasserstein Procrustes with finding Wasserstein barycenter of multiple datasets?

I would like to know your opinion on this. Thank you!

**Comment by claying** [comment]
Hi @vaseline555 

Thank you for your interest in our work. It is indeed possible to extend our work to align multiple datasets by introducing additional alignment regularization between each pair of datasets. Additionally, I think using Wasserstein barycenter instead of Wasserstein Procrustes in the embedding space would indeed be a natural direction to accelerate the alignment of multiple datasets. I look forward to how it works if you want to test it!

**Comment by vaseline555** [comment]
Thank you for your comments. Hope you have a nice Friday! 😄
